# Generated by Django 2.1 on 2018-08-09 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_area', models.CharField(choices=[('1', 'Policies'), ('2', 'Billing'), ('3', 'Claims'), ('4', 'Reports')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'Done'), ('2', 'In progress'), ('3', 'Blocked'), ('4', 'Delayed')], max_length=1)),
                ('target_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
