# Generated by Django 2.1 on 2018-08-13 22:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.CharField(choices=[('A', 'John Snow'), ('B', 'Danaerys Targayen'), ('C', 'Tyrion Lannister'), ('D', 'Oberyn Martell')], max_length=2)),
                ('description', models.TextField()),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_area', models.CharField(choices=[('1', 'Policies'), ('2', 'Billing'), ('3', 'Claims'), ('4', 'Reports')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'Done'), ('2', 'In progress'), ('3', 'Blocked'), ('4', 'Delayed')], max_length=1)),
                ('target_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
